import Head from "next/head";
import { useState, useEffect } from "react";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Testimonials from "../components/Testimonials";
import Trips from "../components/Trips";
import Stats from "../components/Stats";
import Email from "../components/Email";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Explorers | Tours and Travel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Trips heading="Popular destinations...." />
      <Testimonials />
      <Stats />
      <Email />
      <Footer />
    </>
  );
}
